name: buildWindows
on: workflow_dispatch
jobs:
  buildAll:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.0.2 # This doesn't solve the issue of not finding vs2010. need to allow it to work on VS2019
      - name: Fetch Dependencies and Build
        run: | # Many dependencies are not found. Because we are missing 3rdPartyPublic?
          ant -f buildscripts/fetchdeps.xml  
          ant stage -Dmm.build.failonerror=false
